apiVersion: apps/v1 
kind: Deployment
metadata:
  name: etcd-operator
spec:
  selector:
      matchLabels:
        app: etcd-operator
  replicas: 2
  template:
    metadata:
      labels:
        app: etcd-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - etcd-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - name: etcd-operator
        image: daizf/etcd-operator:v0.21.14
        command:
        - etcd-operator
        - -create-crd=false
        # Uncomment to act for resources in all namespaces. More information in doc/user/clusterwide.md
        #- -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8080
