{{- if .Values.deployments.restoreOperator }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.restoreOperator.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: {{ template "etcd-restore-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - protocol: TCP
    name: http-etcd-restore-port
    port: {{ .Values.restoreOperator.port }}
  selector:
    app: {{ template "etcd-restore-operator.name" . }}
    release: {{ .Release.Name }}
{{- end }}
