apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-backup-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: etcd-backup-operator
  template:
    metadata:
      labels:
        name: etcd-backup-operator
    spec:
      containers:
      - name: etcd-backup-operator
        image: daizf/etcd-operator:v0.21.14
        command:
        - etcd-backup-operator
        - -create-crd=false
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
