apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-periodic-backup-oss
spec:
  backupPolicy:
    # 0 > enable periodic backup
    backupIntervalInSecond: 125
    maxBackups: 4
  etcdEndpoints:
    -  http://example-etcd-cluster-client:2379
  storageType: OSS
  oss:
    endpoint: http://oss-cn-hongkong.aliyuncs.com
    ossSecret: aliyun-oss
    path: etcd-backups-bucket/etcd.backup
