apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-restore-operator
  labels:
    app: etcd-restore-operator
spec:
  replicas: 2
  selector:
     matchLabels:
       app: etcd-restore-operator
  template:
    metadata:
      labels:
        app: etcd-restore-operator
    spec:
      nodeSelector:
        esk.ecloud.10086.cn/apps: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - etcd-restore-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - name: etcd-restore-operator
        image: cis-hub-fujian-1.cmecloud.cn/dzf/etcd-operator:v0.21.14
        command:
        - etcd-restore-operator
        - -create-crd=false
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
